name: Hello World

on:
  push:
    branches:
      - main  # Push events will trigger this workflow for the 'main' branch

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"
